name: Update World Cup Results

on:
  schedule:
    - cron: '0 */2 * * *'

  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-results:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install requests pandas

      - name: Run Update Script
        run: |
          python py_files/update_results.py

      - name: Commit Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git add data/world_cup_2026_live_results.json

          git diff --staged --quiet || git commit -m "Auto update World Cup results"

          git push